### ISSUE TITLE
Task: Create Player Movement

### ISSUE THREAD

**Issue by rishisahoo** [towel4/flappy-ghost#19]
Supports story #29 

	•	Test Case Description: Verify that the player can control the character’s movement smoothly.
	•	Test Steps:
	•	Open the game and start a run.
	•	Swipe left, right, up, and down to change the character’s direction.
	•	Expected Results: The character responds accurately to swipes, moving left, right, up, and down as expected.
	•	Actual Results (to be filled during testing):
	•	Pass/Fail (to be filled during testing):

**Comment by towel4** [comment]
won't be operating on swipes but clicks. one button/key input to control how the character moves
