### ISSUE TITLE
Task: Scoreboard

### ISSUE THREAD

**Issue by rishisahoo** [towel4/flappy-ghost#27]
supports story #33 and story #17

**Comment by PeteyA700** [comment]
1. **Basic Functionality Test**
   - Description: Verify that the scoreboard displays correctly after a game session.
   - Test Steps: Complete a game session and observe the scoreboard.
   - Expected Result: The scoreboard should accurately display player names, scores, and ranks.

2. **High Score Test**
   - Description: Test if the scoreboard correctly updates and displays a new high score.
   - Test Steps: Achieve a score higher than the current high scores and check the scoreboard.
   - Expected Result: The new high score should be correctly displayed at the top of the scoreboard.

3. **Multiple Players Test**
   - Description: Ensure the scoreboard correctly handles multiple players.
   - Test Steps: Have multiple players complete a game session and view the scoreboard.
   - Expected Result: All player scores should be displayed in the correct order.

4. **Tie Situation Test**
   - Description: Verify the scoreboard's behavior in a tie situation.
   - Test Steps: Create a scenario where at least two players achieve the same score.
   - Expected Result: The scoreboard should correctly reflect the tie, possibly by sharing ranks or using another defined method.

5. **Data Persistence Test**
   - Description: Check if the scoreboard maintains score data over time.
   - Test Steps: Revisit the scoreboard after restarting the game or system.
   - Expected Result: Previous scores should still be accurately displayed.

6. **Scoreboard Limit Test**
   - Description: Test the behavior when the number of scores exceeds the scoreboard's display limit.
   - Test Steps: Ensure more scores are recorded than the scoreboard can display.
   - Expected Result: The scoreboard should display only the top scores up to its limit.

7. **Invalid Score Input Handling**
   - Description: Test how the scoreboard handles invalid or corrupt score data.
   - Test Steps: Manually input or simulate corrupt/invalid score data.
   - Expected Result: The scoreboard should either correct the data, ignore it, or display an error, depending on the design.

8. **User Interface Responsiveness**
   - Description: Ensure that the scoreboard UI responds well under different conditions.
   - Test Steps: Access the scoreboard under various conditions, such as different screen resolutions, online/offline modes.
   - Expected Result: The scoreboard should be consistently responsive and legible.
   
9. **Accessibility Test**
    - Description: Verify that the scoreboard is accessible to all players, including those with disabilities.
    - Test Steps: Use accessibility tools (screen readers, high-contrast modes) to interact with the scoreboard.
    - Expected Result: The scoreboard should be fully functional and accessible through these tools. 

Each test case should be documented with clear steps and expected outcomes to ensure thorough and effective testing of the scoreboard.
