### ISSUE TITLE
Task: Ghost Sound

### ISSUE THREAD

**Issue by rishisahoo** [towel4/flappy-ghost#39]
Supports story #17

**Comment by PeteyA700** [comment]
Sound Effect by <a href="https://pixabay.com/users/shut_up_ghost-32917765/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=168411">Ghostie Ghost</a> from <a href="https://pixabay.com/sound-effects//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=168411">Pixabay</a>
